// Frontend/src/views/AlumnosView.jsx
import { useEffect, useState } from 'react';
import { api } from '../api/client';
import { exportAlumnos } from '../utils/exportAlumnos';
import EditAlumnoModal from '../components/EditAlumnoModal';
import HeadTotals from '../components/HeadTotals';

function AlumnosView({ term, carrera, grupo, onBack, onMessage }) {
  const [alumnos, setAlumnos] = useState(null);
  const [isExporting, setIsExporting] = useState(false);
  const [editingAlumno, setEditingAlumno] = useState(null);

  const mujeres = alumnos === null ? null : alumnos.filter((alumno) => alumno.genero === 'F').length;
  const hombres = alumnos === null ? null : alumnos.length - mujeres;

  const fetchAlumnos = () => {
    const filters = grupo.sinGrupo
      ? { carrera: [carrera.id], sinAsignar: true }
      : { secuencia: [grupo.secuencia] };
    return api
      .queryAlumnos(term.id, filters)
      .then((res) => setAlumnos(res.items))
      .catch((err) => onMessage({ text: `No se pudieron cargar los alumnos: ${err.message}`, type: 'error' }));
  };

  useEffect(() => {
    fetchAlumnos();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [term.id, carrera.id, grupo.id]);

  const handleExport = async () => {
    setIsExporting(true);
    try {
      const filename = grupo.sinGrupo
        ? `${term.descripcion} - ${carrera.descripcion} - Sin grupo.xlsx`
        : `${term.descripcion} - ${grupo.secuencia}.xlsx`;
      const result = await exportAlumnos(alumnos, filename);
      if (result.cancelled) {
        onMessage({ text: 'Exportación cancelada.', type: 'error' });
        return;
      }
      onMessage({
        text: result.location === 'descargas'
          ? `"${result.name}" se descargó a tu carpeta de Descargas.`
          : `"${result.name}" guardado.`,
        type: 'success',
      });
    } catch (err) {
      onMessage({ text: `Error exportando: ${err.message}`, type: 'error' });
    } finally {
      setIsExporting(false);
    }
  };

  const handleSaved = () => {
    setEditingAlumno(null);
    fetchAlumnos();
  };

  return (
    <div className="page">
      <button className="btn-back" onClick={onBack}>← Volver a Grupos</button>

      <div className="page-head">
        <div>
          <h2>{grupo.sinGrupo ? 'Alumnos sin grupo' : `Alumnos del grupo ${grupo.secuencia}`}</h2>
          <p className="muted">
            {term.descripcion} · {carrera.descripcion}
            {!grupo.sinGrupo && ` · ${grupo.turno === 'M' ? 'Matutino' : 'Vespertino'}`}
          </p>
          <HeadTotals
            stats={[
              { label: alumnos?.length === 1 ? 'alumno' : 'alumnos', value: alumnos?.length ?? null },
              { label: 'hombres', value: hombres },
              { label: 'mujeres', value: mujeres },
            ]}
          />
        </div>
        <button className="btn-file" onClick={handleExport} disabled={isExporting || !alumnos?.length}>
          {isExporting ? 'Exportando…' : 'Exportar Excel'}
        </button>
      </div>

      {alumnos === null && <p className="loading-state">Cargando…</p>}

      {alumnos !== null && alumnos.length === 0 && (
        <div className="empty-state">No hay alumnos que mostrar aquí.</div>
      )}

      {alumnos !== null && alumnos.length > 0 && (
        <div className="table-scroll">
          <table className="students-table">
            <thead>
              <tr>
                <th>PR</th>
                <th>Boleta</th>
                <th>Nombre</th>
                <th>Género</th>
                <th>Promedio</th>
                <th>Distancia (km)</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {alumnos.map((alumno) => (
                <tr key={alumno.pr}>
                  <td>{alumno.pr}</td>
                  <td>{alumno.boleta ?? '—'}</td>
                  <td>{alumno.nombre}</td>
                  <td>{alumno.genero === 'F' ? 'Mujer' : 'Hombre'}</td>
                  <td>{alumno.promedio ?? '—'}</td>
                  <td>{alumno.distanceMeters != null ? Math.round(alumno.distanceMeters / 100) / 10 : '—'}</td>
                  <td>
                    <button className="btn-edit" onClick={() => setEditingAlumno(alumno)}>Editar</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {editingAlumno && (
        <EditAlumnoModal
          alumno={editingAlumno}
          term={term}
          carrera={carrera}
          onClose={() => setEditingAlumno(null)}
          onSaved={handleSaved}
          onMessage={onMessage}
        />
      )}
    </div>
  );
}

export default AlumnosView;

// Frontend/src/views/AlumnosView.vue
<script setup lang="ts">
import { computed, ref, watchEffect } from 'vue';
import { useRouter } from 'vue-router';
import { useToast } from 'primevue/usetoast';
import Button from 'primevue/button';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import { api } from '@/api/client';
import { useBreadcrumbStore } from '@/stores/breadcrumb';
import { exportAlumnos } from '@/utils/exportAlumnos';
import EditAlumnoModal from '@/components/EditAlumnoModal.vue';
import HeadTotals from '@/components/HeadTotals.vue';
import type { AlumnoRow, CarreraConGrupos, GrupoConAlumnos, Term } from '@/types/api';

const props = defineProps<{ termId: number; carreraId: number; grupoId: string }>();

const router = useRouter();
const toast = useToast();
const breadcrumb = useBreadcrumbStore();

const term = ref<Term | null>(null);
const carrera = ref<CarreraConGrupos | null>(null);
const grupo = ref<GrupoConAlumnos | null>(null);
const isSinGrupo = () => props.grupoId === 'sin-grupo';

const alumnos = ref<AlumnoRow[] | null>(null);
const isExporting = ref(false);
const editingAlumno = ref<AlumnoRow | null>(null);

const mujeres = computed(() =>
  alumnos.value === null ? null : alumnos.value.filter((a) => a.genero === 'F').length,
);
const hombres = computed(() =>
  alumnos.value === null || mujeres.value === null ? null : alumnos.value.length - mujeres.value,
);

async function fetchAlumnos() {
  const filters = isSinGrupo()
    ? { carrera: [props.carreraId], sinAsignar: true }
    : { secuencia: [grupo.value?.secuencia ?? ''] };
  try {
    const res = await api.queryAlumnos(props.termId, filters);
    alumnos.value = res.items;
  } catch (err) {
    toast.add({
      severity: 'error',
      summary: 'No se pudieron cargar los alumnos',
      detail: err instanceof Error ? err.message : String(err),
      life: 5000,
    });
  }
}

watchEffect(async () => {
  const { termId, carreraId, grupoId } = props;
  alumnos.value = null;
  try {
    const [termsRes, carrerasRes, gruposRes] = await Promise.all([
      api.listTerms(),
      api.getCarrerasPorCiclo(termId),
      api.getGruposPorCarrera(termId, carreraId),
    ]);
    term.value = termsRes.items.find((t) => t.id === termId) ?? null;
    carrera.value = carrerasRes.items.find((c) => c.id === carreraId) ?? null;
    grupo.value =
      grupoId === 'sin-grupo'
        ? null
        : (gruposRes.items.find((g) => String(g.id) === grupoId) ?? null);

    breadcrumb.setItems([
      { label: 'Ciclos', to: '/ciclos', command: () => router.push({ name: 'ciclos' }) },
      {
        label: term.value?.descripcion ?? `Ciclo ${termId}`,
        to: `/ciclos/${termId}/carreras`,
        command: () => router.push({ name: 'carreras', params: { termId } }),
      },
      {
        label: carrera.value?.descripcion ?? `Carrera ${carreraId}`,
        to: `/ciclos/${termId}/carreras/${carreraId}/grupos`,
        command: () => router.push({ name: 'grupos', params: { termId, carreraId } }),
      },
      {
        label:
          grupoId === 'sin-grupo' ? 'Sin grupo' : (grupo.value?.secuencia ?? `Grupo ${grupoId}`),
      },
    ]);

    await fetchAlumnos();
  } catch (err) {
    toast.add({
      severity: 'error',
      summary: 'No se pudo cargar la información del grupo',
      detail: err instanceof Error ? err.message : String(err),
      life: 5000,
    });
  }
});

async function handleExport() {
  if (!alumnos.value) return;
  isExporting.value = true;
  try {
    const filename = isSinGrupo()
      ? `${term.value?.descripcion ?? props.termId} - ${carrera.value?.descripcion ?? props.carreraId} - Sin grupo.xlsx`
      : `${term.value?.descripcion ?? props.termId} - ${grupo.value?.secuencia ?? props.grupoId}.xlsx`;
    const result = await exportAlumnos(alumnos.value, filename);
    if ('cancelled' in result) {
      toast.add({ severity: 'warn', summary: 'Exportación cancelada', life: 4000 });
      return;
    }
    toast.add({
      severity: 'success',
      summary:
        result.location === 'descargas'
          ? `"${result.name}" descargado`
          : `"${result.name}" guardado`,
      life: 4000,
    });
  } catch (err) {
    toast.add({
      severity: 'error',
      summary: 'Error exportando',
      detail: err instanceof Error ? err.message : String(err),
      life: 5000,
    });
  } finally {
    isExporting.value = false;
  }
}

function handleSaved() {
  editingAlumno.value = null;
  void fetchAlumnos();
}
</script>

<template>
  <div class="page">
    <button
      type="button"
      class="btn-back"
      @click="router.push({ name: 'grupos', params: { termId, carreraId } })"
    >
      <i class="pi pi-arrow-left" /> Volver a Grupos
    </button>

    <div class="page-head">
      <div>
        <h2>
          {{
            isSinGrupo() ? 'Alumnos sin grupo' : `Alumnos del grupo ${grupo?.secuencia ?? grupoId}`
          }}
        </h2>
        <p>
          {{ term?.descripcion ?? '…' }} · {{ carrera?.descripcion ?? '…' }}
          <template v-if="!isSinGrupo() && grupo"
            >· {{ grupo.turno === 'M' ? 'Matutino' : 'Vespertino' }}</template
          >
        </p>
        <HeadTotals
          :stats="[
            { label: alumnos?.length === 1 ? 'alumno' : 'alumnos', value: alumnos?.length ?? null },
            { label: 'hombres', value: hombres },
            { label: 'mujeres', value: mujeres },
          ]"
        />
      </div>
      <Button
        label="Exportar Excel"
        icon="pi pi-file-export"
        severity="secondary"
        outlined
        :loading="isExporting"
        :disabled="!alumnos?.length"
        @click="handleExport"
      />
    </div>

    <p v-if="alumnos === null" class="loading-state">Cargando…</p>

    <div v-else-if="alumnos.length === 0" class="empty-state">No hay alumnos que mostrar aquí.</div>

    <DataTable v-else :value="alumnos" size="small" scrollable scroll-height="65vh">
      <Column field="pr" header="PR" />
      <Column field="boleta" header="Boleta" sortable>
        <template #body="{ data }">{{ data.boleta ?? '—' }}</template>
      </Column>
      <Column field="nombre" header="Nombre" sortable />
      <Column header="Género">
        <template #body="{ data }">{{ data.genero === 'F' ? 'Mujer' : 'Hombre' }}</template>
      </Column>
      <Column field="promedio" header="Promedio" sortable>
        <template #body="{ data }">{{ data.promedio ?? '—' }}</template>
      </Column>
      <Column field="distanceMeters" header="Distancia (km)" sortable>
        <template #body="{ data }">
          {{ data.distanceMeters != null ? Math.round(data.distanceMeters / 100) / 10 : '—' }}
        </template>
      </Column>
      <Column header="">
        <template #body="{ data }">
          <Button
            label="Editar"
            size="small"
            severity="secondary"
            outlined
            @click="editingAlumno = data"
          />
        </template>
      </Column>
    </DataTable>

    <EditAlumnoModal
      v-if="editingAlumno"
      :alumno="editingAlumno"
      :term-id="termId"
      :carrera-id="carreraId"
      @close="editingAlumno = null"
      @saved="handleSaved"
    />
  </div>
</template>
