// Frontend/src/views/GruposView.vue
<script setup lang="ts">
import { computed, ref, watchEffect } from 'vue';
import { useRouter } from 'vue-router';
import { useToast } from 'primevue/usetoast';
import Tag from 'primevue/tag';
import Button from 'primevue/button';
import { api } from '@/api/client';
import { useBreadcrumbStore } from '@/stores/breadcrumb';
import { exportAlumnos } from '@/utils/exportAlumnos';
import HeadTotals from '@/components/HeadTotals.vue';
import EntityCard from '@/components/EntityCard.vue';
import type { CarreraConGrupos, GrupoConAlumnos, Term } from '@/types/api';

const props = defineProps<{ termId: number; carreraId: number }>();

const router = useRouter();
const toast = useToast();
const breadcrumb = useBreadcrumbStore();

const term = ref<Term | null>(null);
const carrera = ref<CarreraConGrupos | null>(null);
const grupos = ref<GrupoConAlumnos[] | null>(null);
const sinGrupo = ref<number | null>(null);
const isExporting = ref(false);

const asignados = computed(() =>
  grupos.value === null ? null : grupos.value.reduce((acc, g) => acc + g.totalAlumnos, 0),
);
const cupo = computed(() =>
  grupos.value === null ? null : grupos.value.reduce((acc, g) => acc + g.cupo, 0),
);
const totalAlumnos = computed(() =>
  asignados.value === null ? null : asignados.value + (sinGrupo.value ?? 0),
);

watchEffect(async () => {
  const { termId, carreraId } = props;
  grupos.value = null;
  sinGrupo.value = null;
  try {
    const [termsRes, carrerasRes, gruposRes, sinGrupoRes] = await Promise.all([
      api.listTerms(),
      api.getCarrerasPorCiclo(termId),
      api.getGruposPorCarrera(termId, carreraId),
      api.queryAlumnos(termId, { carrera: [carreraId], sinAsignar: true }),
    ]);
    term.value = termsRes.items.find((t) => t.id === termId) ?? null;
    carrera.value = carrerasRes.items.find((c) => c.id === carreraId) ?? null;
    grupos.value = gruposRes.items;
    sinGrupo.value = sinGrupoRes.total;

    breadcrumb.setItems([
      { label: 'Ciclos', to: '/ciclos' },
      { label: term.value?.descripcion ?? `Ciclo ${termId}`, to: `/ciclos/${termId}/carreras` },
      { label: carrera.value?.descripcion ?? `Carrera ${carreraId}` },
    ]);
  } catch (err) {
    toast.add({
      severity: 'error',
      summary: 'No se pudieron cargar los grupos',
      detail: err instanceof Error ? err.message : String(err),
      life: 5000,
    });
  }
});

function selectGrupo(grupoId: string) {
  void router.push({
    name: 'alumnos',
    params: { termId: props.termId, carreraId: props.carreraId, grupoId },
  });
}

async function handleExport() {
  isExporting.value = true;
  try {
    const alumnos = await api.queryAlumnos(props.termId, { carrera: [props.carreraId] });
    const filename = `${term.value?.descripcion ?? props.termId} - ${carrera.value?.descripcion ?? props.carreraId}.xlsx`;
    const result = await exportAlumnos(alumnos.items, filename);
    if ('cancelled' in result) {
      toast.add({ severity: 'warn', summary: 'Exportación cancelada', life: 4000 });
      return;
    }
    toast.add({
      severity: 'success',
      summary:
        result.location === 'descargas'
          ? `"${result.name}" descargado`
          : `"${result.name}" guardado`,
      life: 4000,
    });
  } catch (err) {
    toast.add({
      severity: 'error',
      summary: 'Error exportando',
      detail: err instanceof Error ? err.message : String(err),
      life: 5000,
    });
  } finally {
    isExporting.value = false;
  }
}
</script>

<template>
  <div class="page">
    <button
      type="button"
      class="btn-back"
      @click="router.push({ name: 'carreras', params: { termId } })"
    >
      <i class="pi pi-arrow-left" /> Volver a Carreras
    </button>

    <div class="page-head">
      <div>
        <h2>Grupos</h2>
        <p>{{ term?.descripcion ?? '…' }} · {{ carrera?.descripcion ?? '…' }}</p>
        <HeadTotals
          :stats="[
            { label: grupos?.length === 1 ? 'grupo' : 'grupos', value: grupos?.length ?? null },
            { label: 'alumnos', value: totalAlumnos },
            { label: 'lugares de cupo', value: cupo },
            { label: 'sin grupo', value: sinGrupo && sinGrupo > 0 ? sinGrupo : null },
          ]"
        />
      </div>
      <Button
        label="Exportar Excel de la carrera"
        icon="pi pi-file-export"
        severity="secondary"
        outlined
        :loading="isExporting"
        @click="handleExport"
      />
    </div>

    <p v-if="grupos === null" class="loading-state">Cargando…</p>

    <div v-else-if="grupos.length === 0 && sinGrupo === 0" class="empty-state">
      Esta carrera no tiene grupos en este ciclo.
    </div>

    <div v-else-if="grupos.length > 0 || (sinGrupo ?? 0) > 0" class="entity-grid">
      <EntityCard
        v-for="grupo in grupos"
        :key="grupo.id"
        :title="grupo.secuencia"
        @click="selectGrupo(String(grupo.id))"
      >
        <Tag severity="success" :value="grupo.turno === 'M' ? 'Matutino' : 'Vespertino'" />
        <Tag severity="success" :value="`${grupo.totalAlumnos} / ${grupo.cupo} alumnos`" />
      </EntityCard>

      <EntityCard
        v-if="sinGrupo && sinGrupo > 0"
        title="Sin grupo"
        @click="selectGrupo('sin-grupo')"
      >
        <Tag severity="success" :value="`${sinGrupo} alumno${sinGrupo === 1 ? '' : 's'}`" />
      </EntityCard>
    </div>
  </div>
</template>

// Frontend/src/views/GruposView.jsx
import { useEffect, useState } from 'react';
import { api } from '../api/client';
import { exportAlumnos } from '../utils/exportAlumnos';
import HeadTotals from '../components/HeadTotals';

function GruposView({ term, carrera, onSelectGrupo, onBack, onMessage }) {
  const [grupos, setGrupos] = useState(null);
  const [sinGrupo, setSinGrupo] = useState(null);
  const [isExporting, setIsExporting] = useState(false);

  const asignados = grupos === null ? null : grupos.reduce((acc, grupo) => acc + grupo.totalAlumnos, 0);
  const cupo = grupos === null ? null : grupos.reduce((acc, grupo) => acc + grupo.cupo, 0);
  const totalAlumnos = asignados === null ? null : asignados + (sinGrupo ?? 0);

  useEffect(() => {
    api
      .getGruposPorCarrera(term.id, carrera.id)
      .then((res) => setGrupos(res.items))
      .catch((err) => onMessage({ text: `No se pudieron cargar los grupos: ${err.message}`, type: 'error' }));
    api
      .queryAlumnos(term.id, { carrera: [carrera.id], sinAsignar: true })
      .then((res) => setSinGrupo(res.total))
      .catch((err) => onMessage({ text: `No se pudo cargar el conteo de alumnos sin grupo: ${err.message}`, type: 'error' }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [term.id, carrera.id]);

  const handleExport = async () => {
    setIsExporting(true);
    try {
      const alumnos = await api.queryAlumnos(term.id, { carrera: [carrera.id] });
      const result = await exportAlumnos(alumnos.items, `${term.descripcion} - ${carrera.descripcion}.xlsx`);
      if (result.cancelled) {
        onMessage({ text: 'Exportación cancelada.', type: 'error' });
        return;
      }
      onMessage({
        text: result.location === 'descargas'
          ? `"${result.name}" se descargó a tu carpeta de Descargas.`
          : `"${result.name}" guardado.`,
        type: 'success',
      });
    } catch (err) {
      onMessage({ text: `Error exportando: ${err.message}`, type: 'error' });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="page">
      <button className="btn-back" onClick={onBack}>← Volver a Carreras</button>

      <div className="page-head">
        <div>
          <h2>Grupos</h2>
          <p className="muted">{term.descripcion} · {carrera.descripcion}</p>
          <HeadTotals
            stats={[
              { label: grupos?.length === 1 ? 'grupo' : 'grupos', value: grupos?.length ?? null },
              { label: 'alumnos', value: totalAlumnos },
              { label: 'lugares de cupo', value: cupo },
              { label: 'sin grupo', value: sinGrupo > 0 ? sinGrupo : null },
            ]}
          />
        </div>
        <button className="btn-file" onClick={handleExport} disabled={isExporting}>
          {isExporting ? 'Exportando…' : 'Exportar Excel de la carrera'}
        </button>
      </div>

      {grupos === null && <p className="loading-state">Cargando…</p>}

      {grupos !== null && grupos.length === 0 && sinGrupo === 0 && (
        <div className="empty-state">Esta carrera no tiene grupos en este ciclo.</div>
      )}

      {grupos !== null && (grupos.length > 0 || sinGrupo > 0) && (
        <div className="entity-grid">
          {grupos.map((grupo) => (
            <button key={grupo.id} className="entity-card" onClick={() => onSelectGrupo(grupo)}>
              <div>
                <div className="entity-card__title">{grupo.secuencia}</div>
                <div className="entity-card__meta">
                  <span className="badge">{grupo.turno === 'M' ? 'Matutino' : 'Vespertino'}</span>
                  <span className="badge">{grupo.totalAlumnos} / {grupo.cupo} alumnos</span>
                </div>
              </div>
              <span className="entity-card__chevron">›</span>
            </button>
          ))}

          {sinGrupo !== null && sinGrupo > 0 && (
            <button
              className="entity-card"
              onClick={() => onSelectGrupo({ id: 'sin-grupo', secuencia: null, turno: null, cupo: null, sinGrupo: true })}
            >
              <div>
                <div className="entity-card__title">Sin grupo</div>
                <div className="entity-card__meta">
                  <span className="badge">{sinGrupo} alumno{sinGrupo === 1 ? '' : 's'}</span>
                </div>
              </div>
              <span className="entity-card__chevron">›</span>
            </button>
          )}
        </div>
      )}
    </div>
  );
}

export default GruposView;
